### PR TITLE
PT-1807 | Upgrade @apollo/client, HDS, RHHC, Vite related packages & remove warnings from tests

### PR DESCRIPTION
**Pull request by karisal-anders**
## Description :sparkles:

Upgrade packages:
 - @apollo/client to ^3.10.1, and HDS & RHHC to latest
 - all vite related packages to latest

Remove warnings from tests

### Related :handshake:

- [PT-1807](https://helsinkisolutionoffice.atlassian.net/browse/PT-1807)
- Continuation in PR #367 

## Testing :alembic:

Please use node v20 to test (See [Dockerfile](https://github.com/City-of-Helsinki/palvelutarjotin-admin/blob/PT-1807-upgrade-and-cleanup/Dockerfile#L2)).

### Automated tests :gear:️

Tests [ran](https://dev.azure.com/City-of-Helsinki/kultus/_build/results?buildId=208881&view=logs&jobId=8267e077-3a31-5bba-93c5-4b3e55896ad0&j=8267e077-3a31-5bba-93c5-4b3e55896ad0&t=f8bdbb17-be9a-593e-dc0b-831a1df4a0a7) in CI/CD pipeline without warnings except:
```
One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.

babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.
```
which **won't be handled** in this PR, but as part of PR #367 

## Additional notes :spiral_notepad:

[PT-1807]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr363.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr363.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr363.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr363.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr363.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr363.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr363.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr363.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr363.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr363.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — COMMENTED** [review]
I got this kind of messages when I ran the tests 
```
(node:45499) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:45511) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:45506) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Also, the tests didn't pass 

```
 Test Files  72 passed | 2 skipped (74)
      Tests  242 passed | 9 skipped (251)
     Errors  17 errors
   Start at  13:31:32
   Duration  114.51s (transform 119.59s, setup 214.07s, collect 694.21s, tests 522.97s, environment 148.27s, prepare 23.06s)
```

All the errors were like this, but for different files:

```
This error originated in "src/domain/event/__tests__/CreateEventPage.test.tsx" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
The latest test that might've caused the error is "renders current UI language (en) first when translatable fields are rendered". It might mean one of the following:
- The error was thrown, while Vitest was running this test.
- If the error occurred after the test had been completed, this was the last documented test before it was thrown.
```

----

A new try after all the node_modules were reinstalled:

```
This error originated in "src/domain/event/__tests__/CreateEventPage.test.tsx" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
The latest test that might've caused the error is "initializes copied event correctly". It might mean one of the following:
- The error was thrown, while Vitest was running this test.
- If the error occurred after the test had been completed, this was the last documented test before it was thrown.
---

 Test Files  1 failed | 71 passed | 2 skipped (74)
      Tests  1 failed | 241 passed | 9 skipped (251)
     Errors  17 errors
   Start at  13:37:40
   Duration  107.83s (transform 109.51s, setup 202.54s, collect 626.50s, tests 503.69s, environment 147.25s, prepare 22.31s)
```

**Comment by nikomakela** [comment]
This fixes the unit test issue on my local machine https://github.com/City-of-Helsinki/palvelutarjotin-admin/pull/366.

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr363.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr363.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
Up for code reviewing again, fixed the idle timer timeout environment variable value in the `.env*` files and a warning related to `vite.config.ts` default export.

**Pull request merged**
