### PR TITLE
PT-1718, PT-1719 | feat: add pEvent.isQueueingAllowed & studyGroup.preferredTimes support

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat: add pEvent.isQueueingAllowed & studyGroup.preferredTimes support

upgrade packages:
- @sentry/browser                         ^7.107.0  →        ^7.110.0
- @testing-library/react                   ^14.2.1  →         ^15.0.1
- @vitest/coverage-v8                       ^1.4.0  →          ^1.5.0
- dompurify                                ^3.0.11  →          ^3.1.0
- hds-design-tokens                         ^3.5.0  →          ^3.7.0
- hds-react                                 ^3.5.0  →          ^3.7.0
- html-react-parser                         ^5.1.9  →         ^5.1.10
- i18next                                 ^23.10.1  →        ^23.11.1
- i18next-browser-languagedetector          ^7.2.0  →          ^7.2.1
- react-helsinki-headless-cms       1.0.0-alpha264  →  1.0.0-alpha273
- sass                                     ^1.72.0  →         ^1.75.0
- typescript                                ^5.4.3  →          ^5.4.5
- vite                                      ^5.2.2  →          ^5.2.8
- vitest                                    ^1.4.0  →          ^1.5.0

also:
 - CreateEventPage.test.tsx:
   - rename defaultFormData to partialDefaultFormData, remove unused
	 fields from it and type it
 - EventBasicInfo.tsx:
   - make mandatoryAdditionalInformation info showing code more succinct
	 and more readable by using `<p></p>` only once and renaming:
	 - eventDetails.basicInfo.mandatoryAdditionalInformationTrueText ->
	   eventDetails.basicInfo.mandatoryAdditionalInformation
	 - eventDetails.basicInfo.mandatoryAdditionalInformationFalseText ->
	   eventDetails.basicInfo.optionalAdditionalInformation
 - EditEventPage.tsx:
   - invalidate edited event from apollo cache in order to make sure the
	 data is shown up to date, without this change the event's card
	 display didn't show event keywords after editing the event, only
	 the specially handled isFree and isQueueingAllowed keywords

refs PT-1718 (pEvent.isQueueingAllowed)
refs PT-1719 (studyGroup.preferredTimes)

### Related :handshake:

[PT-1718](https://helsinkisolutionoffice.atlassian.net/browse/PT-1718) (pEvent.isQueueingAllowed)
[PT-1719](https://helsinkisolutionoffice.atlassian.net/browse/PT-1719) (studyGroup.preferredTimes)

Backend support:
 - https://github.com/City-of-Helsinki/palvelutarjotin/pull/348

End-user UI support:
 - https://github.com/City-of-Helsinki/palvelutarjotin-ui/pull/312

## Screenshots :camera_flash:

<details>
<summary>Create event (fi/sv/en)</summary>

admin-queueing_allowed-create-event-opened-fi
admin-queueing_allowed-create-event-opened-sv
admin-queueing_allowed-create-event-opened-en

</details>

### Queueing allowed

<details>
<summary>Event preview card (fi/sv/en)</summary>

admin-queueing_allowed-event-preview-card-fi
admin-queueing_allowed-event-preview-card-sv
admin-queueing_allowed-event-preview-card-en

</details>

<details>
<summary>Event preview page (fi/sv/en)</summary>

admin-queueing_allowed-event-preview-page-fi
admin-queueing_allowed-event-preview-page-sv
admin-queueing_allowed-event-preview-page-en

</details>

<details>
<summary>Event summary (fi/sv/en)</summary>

admin-queueing_allowed-event-summary-fi
admin-queueing_allowed-event-summary-sv
admin-queueing_allowed-event-summary-en

</details>

<details>
<summary>Event queue registration extra info (fi/sv/en)</summary>

admin-in_queue-fi
admin-in_queue-sv
admin-in_queue-en

</details>

### Queueing not allowed

<details>
<summary>Event preview card (fi/sv/en)</summary>

admin-queueing_not_allowed-event-preview-card-fi
admin-queueing_not_allowed-event-preview-card-sv
admin-queueing_not_allowed-event-preview-card-en

</details>

<details>
<summary>Event preview page (fi/sv/en)</summary>

admin-queueing_not_allowed-event-preview-page-fi
admin-queueing_not_allowed-event-preview-page-sv
admin-queueing_not_allowed-event-preview-page-en

</details>

<details>
<summary>Event summary (fi/sv/en)</summary>

admin-queueing_not_allowed-event-summary-fi
admin-queueing_not_allowed-event-summary-sv
admin-queueing_not_allowed-event-summary-en

</details>

## Additional notes :spiral_notepad:

[PT-1718]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr341.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr341.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr341.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr341.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr341.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — APPROVED** [review]

**Comment by karisal-anders** [comment]
[Force pushed styles](https://github.com/City-of-Helsinki/palvelutarjotin-admin/compare/b3f7b97ae345a0190d729a0d939f89a826d5812b..2b436fed2dd44090d0d255d11f031fdcbb4a9c12) for showing preferred times in admin's queue list's extra information section

**Pull request merged**
