### PR TITLE
PT-1569, PT-1640 | update and clean up README

### PR DESCRIPTION
**Pull request by karisal-anders**
### docs: update and clean up README
 - update tunnistamo related instructions
 - update docker-compose related instructions
 - remove unnecessary URL names where the URL and its name are the same,
   now the URL name can not go out of sync with the URL

refs PT-1569 (ran into trouble following the README.md's instructions)
refs PT-1640 (bug related to "docker-compose up" failing)

### Closes :no_good_woman:

`-`

### Related :handshake:

**[PT-1569](https://helsinkisolutionoffice.atlassian.net/browse/PT-1569)** 
**[PT-1640](https://helsinkisolutionoffice.atlassian.net/browse/PT-1640)** 

## Additional notes :spiral_notepad:

[PT-1569]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PT-1640]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr288.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr288.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr288.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr288.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr288.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — APPROVED** [review]

**Pull request merged**
