### PR TITLE
Enrolment queue table in the occurrence page

### PR DESCRIPTION
**Pull request by nikomakela**
PT-1651.

There is a new table under the enrolments table in the occurrence page. The old table for enrolments lists the enrolments done to occurrence. The new event queue enrolments table lists the queued enrolments added to the PalvelutarjotinEvent.

There are 2 mutations that can be used: 1 to remove the queue enrolment and another one to pick the event queue enrolment to the list of occurrence enrolments. The status of the event queue enrolment will change when the group has at least 1 enrolment done. Thats visible and coloured as a status badge. This is because the event queue instance should still persist in the queue list, because it might be needed in another occurrence.

The notification handling works exactly as it worked earlier. The event queue actions wont send anything to anyone.

image

### CODE REVIEW

**Comment by nikomakela** [comment]
I will add some unit tests still, but the actual implementation should not be affected, so it's reviewable.

- [ ] Add unit tests

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr297.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr297.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr297.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr297.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by nikomakela** [comment]
I still try to fix the warning that the Sonarcloud Qualitygate raises

- [ ] Fix the Sonarcloud Qualitygate warnings

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr297.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr297.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr297.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr297.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-admin-ui branch is deployed to platta: https://kultus-admin-ui-pr297.dev.hel.ninja** :rocket::rocket::rocket:

**Review by melniiv — APPROVED** [review]

**Pull request merged**
